[BASE]
services=["google", "yandex", "always_fail"]
token="PLACE_BOT_TOKEN_HERE"
chat_id="PLACE_CHAT_ID_HERE"

[yandex]
url="http://db:5432"
panic=5
interval=3

[google]
url="http://wordpress:8000"
panic=2
interval=5

[always_fail]
url="https://foo.bar"
panic=2
interval=5