[BASE]
token="PLACE_BOT_TOKEN_HERE"
chat_id="PLACE_CHAT_ID_HERE"

[yandex]
url="https://yandex.ru"
panic=6
interval=3

[google]
url="https://google.com"
panic=2
interval=5

[always_fail]
url="http://foo.com"
panic=2
interval=5
after_panic_delay=10