[BASE]
token="PLACE_BOT_TOKEN_HERE"
chat_id="PLACE_CHAT_ID_HERE"

[yandex]
url="https://yandex.ru"
panic=5
interval=3
success_log="{url} - {status_code} - {time}s Success"
failure_log="{url} - {status_code} - {time}s Fail"

[google]
url="https://google.com"
panic=2
interval=5

[always_fail]
url="https://foo.bar"
panic=2
interval=5
after_panic_delay=10
after_exception_delay=100